'use client'




import "./globals.css";

import { Provider } from "react-redux";
import { store } from "@/lib/store/store";




/*export const metadata: Metadata = {
  title: "SimonBot.AI",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Provider store={store}>
      <body
       
      >
       
        {children }
       
      </body></Provider>
    </html>
  );
}
